import the module

In [1]:
import pickle as p

method used 1. dump 2.dumps 3.load 4.loads

1.dump - serialize the data into a file

2. dumps - serialize the data in memory in secondry memory

3.load - deserialize the data from a file

4.loads = deserialize the data from memory

1. numeric data

In [16]:
a=10;b=23.5;c=9+8j
p_a=p.dumps(a)
p_b=p.dumps(b)
p_c=p.dumps(c)
type(a),type(b),type(c)

(int, float, complex)

In [17]:
type(p_a),type(p_b),type(p_c)

(bytes, bytes, bytes)

In [18]:
print(p_a)
print(p_b)
print(p_c)

b'\x80\x04K\n.'
b'\x80\x04\x95\n\x00\x00\x00\x00\x00\x00\x00G@7\x80\x00\x00\x00\x00\x00.'
b'\x80\x04\x95.\x00\x00\x00\x00\x00\x00\x00\x8c\x08builtins\x94\x8c\x07complex\x94\x93\x94G@"\x00\x00\x00\x00\x00\x00G@ \x00\x00\x00\x00\x00\x00\x86\x94R\x94.'

In [19]:
import sys

In [20]:
print(sys.getsizeof(a),sys.getsizeof(p_a))
print(sys.getsizeof(b),sys.getsizeof(p_b))
print(sys.getsizeof(c),sys.getsizeof(p_c))

28 38
24 54
32 90

In [21]:
d_a=p.loads(p_a)
d_b=p.loads(p_b)
d_c=p.loads(p_c)
print(d_a,d_b,d_c)
type(d_a),type(d_b),type(d_c)

10 23.5 (9+8j)

(int, float, complex)

2. sequence data

In [22]:
l=[1,2,3,'banana',[23,45.7,9-7j]]
p_l=p.dumps(l)
print(type(l),type(p_l))
d_l=p.loads(p_l)
print(l,p_l,d_l,type(d_l))

<class 'list'> <class 'bytes'>
[1, 2, 3, 'banana', [23, 45.7, (9-7j)]] b'\x80\x04\x95P\x00\x00\x00\x00\x00\x00\x00]\x94(K\x01K\x02K\x03\x8c\x06banana\x94]\x94(K\x17G@F\xd9\x99\x99\x99\x99\x9a\x8c\x08builtins\x94\x8c\x07complex\x94\x93\x94G@"\x00\x00\x00\x00\x00\x00G\xc0\x1c\x00\x00\x00\x00\x00\x00\x86\x94R\x94ee.' [1, 2, 3, 'banana', [23, 45.7, (9-7j)]] <class 'list'>

In [26]:
d = {1:'a',2:2,3:52.2}
p_d = p.dumps(d)
print(type(d),type(p_d))

<class 'dict'> <class 'bytes'>

In [27]:
print(p_d)

b'\x80\x04\x95\x1a\x00\x00\x00\x00\x00\x00\x00}\x94(K\x01\x8c\x01a\x94K\x02K\x02K\x03G@J\x19\x99\x99\x99\x99\x9au.'

In [28]:
d_d = p.loads(p_d)
print(d_d)

{1: 'a', 2: 2, 3: 52.2}

picking the data into a file

In [29]:
l1=[1,2,3,'apple']
d1={1:'a',2:'b'}
s1='Hello picking the data'
n1=56.89898
with open('data.pkl','wb')as f:
    p.dump(l1,f)
    p.dump(d1,f)
    p.dump(s1,f)
    p.dump(n1,f)

In [32]:
with open('data.pkl','rb')as f:
    d_l1=p.load(f)
    d_d1=p.load(f)
    d_s1=p.load(f)
    d_n1=p.load(f)
    print(d_l1,d_d1,d_s1,d_n1)

[1, 2, 3, 'apple'] {1: 'a', 2: 'b'} Hello picking the data 56.89898

3. function

In [33]:
def greet(name):
    return f'hello, {name}'

greet('alpha')

'hello, alpha'

In [34]:
p_f=p.dumps(greet)

In [35]:
type(greet), type(p_f)

(function, bytes)

In [37]:
p_f , greet

(b'\x80\x04\x95\x16\x00\x00\x00\x00\x00\x00\x00\x8c\x08__main__\x94\x8c\x05greet\x94\x93\x94.',
 <function __main__.greet(name)>)

In [38]:
l_f=p.loads(p_f)

In [39]:
l_f , type(l_f)

(<function __main__.greet(name)>, function)

4. custom object

In [40]:
class person:
    def __init__(self,name,age):
        self.name = name
        self.age = age
    def __repr__(self):
        return f'Person(name:{self.name},age:{self.age})'

p1=person('alpha',21)

In [41]:
type(p1)

__main__.person

In [44]:

p_p1=p.dumps(p1)
type(p_p1),p_p1

(bytes,
 b'\x80\x04\x956\x00\x00\x00\x00\x00\x00\x00\x8c\x08__main__\x94\x8c\x06person\x94\x93\x94)\x81\x94}\x94(\x8c\x04name\x94\x8c\x05alpha\x94\x8c\x03age\x94K\x15ub.')

5. pandas dataframe

In [45]:
import pandas as pd

In [46]:
data = {'name':['alpha','beta','gamma'],'age':[13,34,23],'city':['bengalore','mysore','manglore']}

In [47]:
df = pd.DataFrame(data)
df

    name  age       city
0  alpha   13  bengalore
1   beta   34     mysore
2  gamma   23   manglore

In [48]:
df.to_pickle('d1.pkl')

In [49]:
d_df=pd.read_pickle('d1.pkl')
d_df

    name  age       city
0  alpha   13  bengalore
1   beta   34     mysore
2  gamma   23   manglore