In [1]:
print('avi')

avi

In [2]:
import pandas as p

In [3]:
df=p.read_csv('sales_r.csv')
df

      Product  Qty  Amount   Region   Customer            City    Unnamed: 6
0     Mobile    10  12,000   south       Rahul     "Bengaluru"           NaN
1      Laptop        45000    North    SHREYA            Delhi           NaN
2  Headphones    5     NaN     west     Arjun           Mumbai           NaN
3     Charger    3   1,200     east      Meera         Kolkata           NaN
4     Camera     2  55,000    South                    Chennai           NaN
5      Tablet          "22     500"      north           Rohan   "New Delhi"
6       Mouse    7     800     west     anita             Pune           NaN
7    Keyboard    4   1,500     East   karthik    "Bhubaneswar"           NaN
8     Monitor          "12     800"      south                     Hyderabad
9     Speaker    6   3,200    west      Vikram       Ahmedabad           NaN

check for missing values per column

In [4]:
df.isna()

   Product    Qty   Amount   Region   Customer   City  Unnamed: 6
0    False  False    False    False      False  False        True
1    False  False    False    False      False  False        True
2    False  False     True    False      False  False        True
3    False  False    False    False      False  False        True
4    False  False    False    False      False  False        True
5    False  False    False    False      False  False       False
6    False  False    False    False      False  False        True
7    False  False    False    False      False  False        True
8    False  False    False    False      False  False       False
9    False  False    False    False      False  False        True

In [5]:
df.isna().sum()

Product       0
 Qty          0
 Amount       1
 Region       0
 Customer     0
 City         0
Unnamed: 6    8
dtype: int64

check for missing values per rows

df.isna().any(axis=1)

In [6]:
df.isna().any(axis=1)

0     True
1     True
2     True
3     True
4     True
5    False
6     True
7     True
8    False
9     True
dtype: bool

check missing cell

In [7]:
df.notna().sum()

Product       10
 Qty          10
 Amount        9
 Region       10
 Customer     10
 City         10
Unnamed: 6     2
dtype: int64

In [8]:
df.notna().any(axis=1).sum()

np.int64(10)

In [9]:
df.head()

      Product  Qty  Amount   Region  Customer          City Unnamed: 6
0     Mobile    10  12,000   south      Rahul   "Bengaluru"        NaN
1      Laptop        45000    North   SHREYA          Delhi        NaN
2  Headphones    5     NaN     west    Arjun         Mumbai        NaN
3     Charger    3   1,200     east     Meera       Kolkata        NaN
4     Camera     2  55,000    South                 Chennai        NaN

cleaning the data perprocessing

clean the column name

In [10]:
df.columns = df.columns.str.strip()

In [11]:
df.columns

Index(['Product', 'Qty', 'Amount', 'Region', 'Customer', 'City', 'Unnamed: 6'], dtype='object')

In [12]:
df.tail()

    Product Qty Amount  Region   Customer            City    Unnamed: 6
5    Tablet        "22    500"      north           Rohan   "New Delhi"
6     Mouse   7    800    west     anita             Pune           NaN
7  Keyboard   4  1,500    East   karthik    "Bhubaneswar"           NaN
8   Monitor        "12    800"      south                     Hyderabad
9   Speaker   6  3,200   west      Vikram       Ahmedabad           NaN

clean the data in the column

In [13]:
df['Amount'] = (df['Amount'].astype(str).str.replace('"','',regex=False).str.replace(',','',regex=False).str.extract(r'(\d+)',expand=False))

In [14]:
df['Amount']

0    12000
1    45000
2      NaN
3     1200
4    55000
5       22
6      800
7     1500
8       12
9     3200
Name: Amount, dtype: object

convert string to numeric

In [15]:
df['Amount']=p.to_numeric(df['Amount'],errors='coerce')
print(df.dtypes)
# errors=coerce make all non numeric data as NaN

Product        object
Qty            object
Amount        float64
Region         object
Customer       object
City           object
Unnamed: 6     object
dtype: object

In [16]:
df['Amount']

0    12000.0
1    45000.0
2        NaN
3     1200.0
4    55000.0
5       22.0
6      800.0
7     1500.0
8       12.0
9     3200.0
Name: Amount, dtype: float64

fill the missing data

1. median is used to fill

In [17]:
df['Amount']=df['Amount'].fillna(df['Amount'].median())

In [18]:
df['Amount']

0    12000.0
1    45000.0
2     1500.0
3     1200.0
4    55000.0
5       22.0
6      800.0
7     1500.0
8       12.0
9     3200.0
Name: Amount, dtype: float64

In [19]:
df['Qty']

0    10
1
2     5
3     3
4     2
5
6     7
7     4
8
9     6
Name: Qty, dtype: object

In [20]:
df['Qty']=p.to_numeric(df['Qty'],errors='coerce')

In [21]:
df['Qty']

0    10.0
1     NaN
2     5.0
3     3.0
4     2.0
5     NaN
6     7.0
7     4.0
8     NaN
9     6.0
Name: Qty, dtype: float64

2. mean is uesd to replace NaN

In [22]:
df['Qty']=df['Qty'].fillna(df['Qty'].mean())

In [23]:
df['Qty']

0    10.000000
1     5.285714
2     5.000000
3     3.000000
4     2.000000
5     5.285714
6     7.000000
7     4.000000
8     5.285714
9     6.000000
Name: Qty, dtype: float64

3. mode is alos used to fill NaN

In [24]:
df.head()

      Product        Qty   Amount   Region  Customer          City Unnamed: 6
0     Mobile   10.000000  12000.0   south      Rahul   "Bengaluru"        NaN
1      Laptop   5.285714  45000.0    North   SHREYA          Delhi        NaN
2  Headphones   5.000000   1500.0     west    Arjun         Mumbai        NaN
3     Charger   3.000000   1200.0     east     Meera       Kolkata        NaN
4     Camera    2.000000  55000.0    South                 Chennai        NaN

drop a column that has 1.NaN 2.not needed for processing

In [25]:
df = df.loc[:,~df.columns.str.contains("^Unnamed")]

In [26]:
df

      Product        Qty   Amount   Region   Customer            City
0     Mobile   10.000000  12000.0   south       Rahul     "Bengaluru"
1      Laptop   5.285714  45000.0    North    SHREYA            Delhi
2  Headphones   5.000000   1500.0     west     Arjun           Mumbai
3     Charger   3.000000   1200.0     east      Meera         Kolkata
4     Camera    2.000000  55000.0    South                    Chennai
5      Tablet   5.285714     22.0     500"      north           Rohan
6       Mouse   7.000000    800.0     west     anita             Pune
7    Keyboard   4.000000   1500.0     East   karthik    "Bhubaneswar"
8     Monitor   5.285714     12.0     800"      south
9     Speaker   6.000000   3200.0    west      Vikram       Ahmedabad

equivalent option

In [27]:
df=df.drop(columns=["Unnamed: 6"])
# give full name of the column
df=df.iloc[:,:-1]
# drop by index position, works only for corner columns
df=df.dropna(axis=1,how="all")
# drop column with all NaN or missing values

KeyError: "['Unnamed: 6'] not found in axis"

In [ ]:
df.head()

      Product        Qty   Amount   Region  Customer          City
0     Mobile   10.000000  12000.0   south      Rahul   "Bengaluru"
1      Laptop   5.285714  45000.0    North   SHREYA          Delhi
2  Headphones   5.000000   1500.0     west    Arjun         Mumbai
3     Charger   3.000000   1200.0     east     Meera       Kolkata
4     Camera    2.000000  55000.0    South                 Chennai

standardize text coumns

In [ ]:
df['Region']=df['Region'].str.strip().str.lower()

C:\Users\Avi Chovatiya\AppData\Local\Temp\ipykernel_17368\2260623519.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Region']=df['Region'].str.strip().str.lower()

In [ ]:
df['Region']

0    south
1    north
2     west
3     east
4    south
5     500"
6     west
7     east
8     800"
9     west
Name: Region, dtype: object

remove quotes in all columns

In [ ]:
df=df.apply(lambda col:col.astype(str).str.replace('"','',regex=False))

In [ ]:
df.head()

      Product                Qty   Amount Region  Customer        City
0     Mobile                10.0  12000.0  south     Rahul   Bengaluru
1      Laptop  5.285714285714286  45000.0  north   SHREYA        Delhi
2  Headphones                5.0   1500.0   west    Arjun       Mumbai
3     Charger                3.0   1200.0   east     Meera     Kolkata
4     Camera                 2.0  55000.0  south               Chennai

In [ ]:
df.tail()

    Product                Qty  Amount Region   Customer          City
5    Tablet  5.285714285714286    22.0    500      north         Rohan
6     Mouse                7.0   800.0   west     anita           Pune
7  Keyboard                4.0  1500.0   east   karthik    Bhubaneswar
8   Monitor  5.285714285714286    12.0    800      south
9   Speaker                6.0  3200.0   west     Vikram     Ahmedabad

processing of data

1. filter the datam

In [ ]:
df['Amount']=df['Amount'].astype('float64')
print(df.dtype)

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [ ]:
df['Amount']=df['Amount'].astype('float64')
print(df.dtypes)

Product      object
Qty          object
Amount      float64
Region       object
Customer     object
City         object
dtype: object

In [ ]:
hsales = df['Amount']>2000

In [ ]:
hsales

0     True
1     True
2    False
3    False
4     True
5    False
6    False
7    False
8    False
9     True
Name: Amount, dtype: bool

create the filtered data frame

In [ ]:
df_high=df[hsales]
df_high

   Product                Qty   Amount Region  Customer        City
0  Mobile                10.0  12000.0  south     Rahul   Bengaluru
1   Laptop  5.285714285714286  45000.0  north   SHREYA        Delhi
4  Camera                 2.0  55000.0  south               Chennai
9  Speaker                6.0   3200.0   west    Vikram   Ahmedabad

to check the total number of rows in a data frame

In [ ]:
len(df)

10

In [ ]:
len(df_high)

4

filtering baesd on multiple conditions

In [ ]:
c_amount = df['Amount']>2000
c_reg = df['Region']=='south'
df_filter=df[c_amount&c_reg]
print(df_filter)
len(df_filter)

   Product   Qty   Amount Region Customer        City
0  Mobile   10.0  12000.0  south    Rahul   Bengaluru
4  Camera    2.0  55000.0  south              Chennai

2

In [ ]:
df_filter1=df[c_amount|c_reg]
print(df_filter1)
len(df_filter1)

   Product                Qty   Amount Region  Customer        City
0  Mobile                10.0  12000.0  south     Rahul   Bengaluru
1   Laptop  5.285714285714286  45000.0  north   SHREYA        Delhi
4  Camera                 2.0  55000.0  south               Chennai
9  Speaker                6.0   3200.0   west    Vikram   Ahmedabad

4

sort the data frame

In [ ]:
df.dtypes

Product      object
Qty          object
Amount      float64
Region       object
Customer     object
City         object
dtype: object

In [ ]:
df['Qty']=df['Qty'].astype('float64')

In [ ]:
df.dtypes

Product      object
Qty         float64
Amount      float64
Region       object
Customer     object
City         object
dtype: object

In [ ]:
df_asc=df.sort_values('Qty')
df_asc

      Product        Qty   Amount Region   Customer          City
4     Camera    2.000000  55000.0  south                  Chennai
3     Charger   3.000000   1200.0   east      Meera       Kolkata
7    Keyboard   4.000000   1500.0   east   karthik    Bhubaneswar
2  Headphones   5.000000   1500.0   west     Arjun         Mumbai
5      Tablet   5.285714     22.0    500      north         Rohan
1      Laptop   5.285714  45000.0  north    SHREYA          Delhi
8     Monitor   5.285714     12.0    800      south
9     Speaker   6.000000   3200.0   west     Vikram     Ahmedabad
6       Mouse   7.000000    800.0   west     anita           Pune
0     Mobile   10.000000  12000.0  south      Rahul     Bengaluru

In [ ]:
df_desc=df.sort_values("Qty",ascending=False)
df_desc

      Product        Qty   Amount Region   Customer          City
0     Mobile   10.000000  12000.0  south      Rahul     Bengaluru
6       Mouse   7.000000    800.0   west     anita           Pune
9     Speaker   6.000000   3200.0   west     Vikram     Ahmedabad
1      Laptop   5.285714  45000.0  north    SHREYA          Delhi
5      Tablet   5.285714     22.0    500      north         Rohan
8     Monitor   5.285714     12.0    800      south
2  Headphones   5.000000   1500.0   west     Arjun         Mumbai
7    Keyboard   4.000000   1500.0   east   karthik    Bhubaneswar
3     Charger   3.000000   1200.0   east      Meera       Kolkata
4     Camera    2.000000  55000.0  south                  Chennai

sort based on multiple columns

In [ ]:
df_msort = df.sort_values(['Region','Amount'])
df_msort

      Product        Qty   Amount Region   Customer          City
5      Tablet   5.285714     22.0    500      north         Rohan
8     Monitor   5.285714     12.0    800      south
3     Charger   3.000000   1200.0   east      Meera       Kolkata
7    Keyboard   4.000000   1500.0   east   karthik    Bhubaneswar
1      Laptop   5.285714  45000.0  north    SHREYA          Delhi
0     Mobile   10.000000  12000.0  south      Rahul     Bengaluru
4     Camera    2.000000  55000.0  south                  Chennai
6       Mouse   7.000000    800.0   west     anita           Pune
2  Headphones   5.000000   1500.0   west     Arjun         Mumbai
9     Speaker   6.000000   3200.0   west     Vikram     Ahmedabad

In [ ]:
df_msort = df.sort_values(['Region','Amount'],ascending=[True,False])

In [ ]:
df_msort

      Product        Qty   Amount Region   Customer          City
5      Tablet   5.285714     22.0    500      north         Rohan
8     Monitor   5.285714     12.0    800      south
7    Keyboard   4.000000   1500.0   east   karthik    Bhubaneswar
3     Charger   3.000000   1200.0   east      Meera       Kolkata
1      Laptop   5.285714  45000.0  north    SHREYA          Delhi
4     Camera    2.000000  55000.0  south                  Chennai
0     Mobile   10.000000  12000.0  south      Rahul     Bengaluru
9     Speaker   6.000000   3200.0   west     Vikram     Ahmedabad
2  Headphones   5.000000   1500.0   west     Arjun         Mumbai
6       Mouse   7.000000    800.0   west     anita           Pune

replace nummeric in string columns

In [ ]:
df.loc[p.to_numeric(df['Region'],errors='coerce').isin([500,800]),'Region'] = 'north'
# temp conversion

In [ ]:
df

      Product        Qty   Amount Region   Customer          City
0     Mobile   10.000000  12000.0  south      Rahul     Bengaluru
1      Laptop   5.285714  45000.0  north    SHREYA          Delhi
2  Headphones   5.000000   1500.0   west     Arjun         Mumbai
3     Charger   3.000000   1200.0   east      Meera       Kolkata
4     Camera    2.000000  55000.0  south                  Chennai
5      Tablet   5.285714     22.0  north      north         Rohan
6       Mouse   7.000000    800.0   west     anita           Pune
7    Keyboard   4.000000   1500.0   east   karthik    Bhubaneswar
8     Monitor   5.285714     12.0  north      south
9     Speaker   6.000000   3200.0   west     Vikram     Ahmedabad

create columns using arithmetic calculations

In [ ]:
df['Tax']=df['Amount']*0.18

In [ ]:
df

      Product        Qty   Amount Region   Customer          City      Tax
0     Mobile   10.000000  12000.0  south      Rahul     Bengaluru  2160.00
1      Laptop   5.285714  45000.0  north    SHREYA          Delhi  8100.00
2  Headphones   5.000000   1500.0   west     Arjun         Mumbai   270.00
3     Charger   3.000000   1200.0   east      Meera       Kolkata   216.00
4     Camera    2.000000  55000.0  south                  Chennai  9900.00
5      Tablet   5.285714     22.0  north      north         Rohan     3.96
6       Mouse   7.000000    800.0   west     anita           Pune   144.00
7    Keyboard   4.000000   1500.0   east   karthik    Bhubaneswar   270.00
8     Monitor   5.285714     12.0  north      south                   2.16
9     Speaker   6.000000   3200.0   west     Vikram     Ahmedabad   576.00

In [ ]:
df[['Amount','Tax']]

    Amount      Tax
0  12000.0  2160.00
1  45000.0  8100.00
2   1500.0   270.00
3   1200.0   216.00
4  55000.0  9900.00
5     22.0     3.96
6    800.0   144.00
7   1500.0   270.00
8     12.0     2.16
9   3200.0   576.00

In [ ]:
df['Totals']=df['Amount']+df['Tax']

In [ ]:
df

,Product,Qty,Amount,Region,Customer,City,Tax,Totals
0,Mobile,10.000000,12000.0,south,Rahul,Bengaluru,2160.00,14160.00
1,Laptop,5.285714,45000.0,north,SHREYA,Delhi,8100.00,53100.00
2,Headphones,5.000000,1500.0,west,Arjun,Mumbai,270.00,1770.00
3,Charger,3.000000,1200.0,east,Meera,Kolkata,216.00,1416.00
4,Camera,2.000000,55000.0,south,,Chennai,9900.00,64900.00
5,Tablet,5.285714,22.0,north,north,Rohan,3.96,25.96
6,Mouse,7.000000,800.0,west,anita,Pune,144.00,944.00
7,Keyboard,4.000000,1500.0,east,karthik,Bhubaneswar,270.00,1770.00
8,Monitor,5.285714,12.0,north,south,,2.16,14.16
9,Speaker,6.000000,3200.0,west,Vikram,Ahmedabad,576.00,3776.00

profile the columns

1. analyzee categorical columns

In [ ]:
df['Region'].value_counts()

Region
north    3
west     3
south    2
east     2
Name: count, dtype: int64

In [ ]:
df['City'].value_counts()

City
 Bengaluru      1
 Delhi          1
 Mumbai         1
Kolkata         1
Chennai         1
Rohan           1
Pune            1
 Bhubaneswar    1
                1
 Ahmedabad      1
Name: count, dtype: int64

summarize categorical

In [ ]:
df['Amount'].describe()

count       10.000000
mean     12023.400000
std      20453.739545
min         12.000000
25%        900.000000
50%       1500.000000
75%       9800.000000
max      55000.000000
Name: Amount, dtype: float64

In [ ]:
df['Region'].describe()

count        10
unique        4
top       north
freq          3
Name: Region, dtype: object

grouping of data

In [ ]:
grp_reg=df.groupby('Region')

In [ ]:
grp_reg

view the group
1.view the group names

In [ ]:
grp_reg.groups.keys()

dict_keys(['east', 'north', 'south', 'west'])

2.view row indexes beloning to each group

In [ ]:
grp_reg.groups

{'east': [3, 7], 'north': [1, 5, 8], 'south': [0, 4], 'west': [2, 6, 9]}

3. view sepcific group

In [ ]:
grp_reg.get_group('north')

   Product       Qty   Amount Region  Customer    City      Tax    Totals
1   Laptop  5.285714  45000.0  north   SHREYA    Delhi  8100.00  53100.00
5   Tablet  5.285714     22.0  north     north   Rohan     3.96     25.96
8  Monitor  5.285714     12.0  north     south             2.16     14.16

4. view all groups

In [ ]:
for name,group in grp_reg:
    print(f'\n----> Group {name}\n')
    print(group)

----> Group east

    Product  Qty  Amount Region   Customer          City    Tax  Totals
3   Charger  3.0  1200.0   east      Meera       Kolkata  216.0  1416.0
7  Keyboard  4.0  1500.0   east   karthik    Bhubaneswar  270.0  1770.0

----> Group north

   Product       Qty   Amount Region  Customer    City      Tax    Totals
1   Laptop  5.285714  45000.0  north   SHREYA    Delhi  8100.00  53100.00
5   Tablet  5.285714     22.0  north     north   Rohan     3.96     25.96
8  Monitor  5.285714     12.0  north     south             2.16     14.16

----> Group south

   Product   Qty   Amount Region Customer        City     Tax   Totals
0  Mobile   10.0  12000.0  south    Rahul   Bengaluru  2160.0  14160.0
4  Camera    2.0  55000.0  south              Chennai  9900.0  64900.0

----> Group west

      Product  Qty  Amount Region Customer        City    Tax  Totals
2  Headphones  5.0  1500.0   west   Arjun       Mumbai  270.0  1770.0
6       Mouse  7.0   800.0   west   anita         Pune  144.0   944.0
9     Speaker  6.0  3200.0   west   Vikram   Ahmedabad  576.0  3776.0

grouping based on multiple columns

In [ ]:
grp_mrge=df.groupby(['Region','City'])

In [ ]:
for n,g in grp_mrge:
    print(f'\n----->Group: {n}\n')
    print(g)

----->Group: ('east', ' Bhubaneswar')

    Product  Qty  Amount Region   Customer          City    Tax  Totals
7  Keyboard  4.0  1500.0   east   karthik    Bhubaneswar  270.0  1770.0

----->Group: ('east', 'Kolkata')

   Product  Qty  Amount Region Customer     City    Tax  Totals
3  Charger  3.0  1200.0   east    Meera  Kolkata  216.0  1416.0

----->Group: ('north', ' ')

   Product       Qty  Amount Region Customer City   Tax  Totals
8  Monitor  5.285714    12.0  north    south       2.16   14.16

----->Group: ('north', ' Delhi')

  Product       Qty   Amount Region  Customer    City     Tax   Totals
1  Laptop  5.285714  45000.0  north   SHREYA    Delhi  8100.0  53100.0

----->Group: ('north', 'Rohan')

  Product       Qty  Amount Region Customer   City   Tax  Totals
5  Tablet  5.285714    22.0  north    north  Rohan  3.96   25.96

----->Group: ('south', ' Bengaluru')

   Product   Qty   Amount Region Customer        City     Tax   Totals
0  Mobile   10.0  12000.0  south    Rahul   Bengaluru  2160.0  14160.0

----->Group: ('south', 'Chennai')

   Product  Qty   Amount Region Customer     City     Tax   Totals
4  Camera   2.0  55000.0  south           Chennai  9900.0  64900.0

----->Group: ('west', ' Ahmedabad')

   Product  Qty  Amount Region Customer        City    Tax  Totals
9  Speaker  6.0  3200.0   west   Vikram   Ahmedabad  576.0  3776.0

----->Group: ('west', ' Mumbai')

      Product  Qty  Amount Region Customer     City    Tax  Totals
2  Headphones  5.0  1500.0   west   Arjun    Mumbai  270.0  1770.0

----->Group: ('west', 'Pune')

  Product  Qty  Amount Region Customer  City    Tax  Totals
6   Mouse  7.0   800.0   west   anita   Pune  144.0   944.0

aggregate the groups

In [ ]:
mreg=grp_mrge['Amount'].sum()
mreg

Region  City
east     Bhubaneswar     1500.0
        Kolkata          1200.0
north                      12.0
         Delhi          45000.0
        Rohan              22.0
south    Bengaluru      12000.0
        Chennai         55000.0
west     Ahmedabad       3200.0
         Mumbai          1500.0
        Pune              800.0
Name: Amount, dtype: float64

custome Aggregation

In [ ]:
summary=df.groupby('Region').agg(
    Total=('Amount','sum'),
    Averge_Amt=('Amount','mean'),
    Total_Tax=('Tax','sum'),
    Average_tax=('Tax','mean'),
    Unique_cutomers=('Customer','nunique')
)

In [ ]:
summary

          Total    Averge_Amt  Total_Tax  Average_tax  Unique_cutomers
Region
east     2700.0   1350.000000     486.00       243.00                2
north   45034.0  15011.333333    8106.12      2702.04                3
south   67000.0  33500.000000   12060.00      6030.00                2
west     5500.0   1833.333333     990.00       330.00                3

combine data frames

In [29]:
sal=p.read_csv('sales.csv')
prod = p.read_csv('products.csv')

In [30]:
sal.columns

Index(['OrderID', 'ProductID', 'Qty', 'Amount', 'Region', 'Customer', 'City',
       'Date'],
      dtype='object')

In [31]:
prod.columns

Index(['ProductID', 'ProductName', 'Category', 'Brand'], dtype='object')

check for uniqueness of the common column

In [33]:
prod['ProductID'].nunique()

8

In [36]:
len(prod)
# if the number of unique occurrences of productId matches the number of records of products the dataFrame can be marged of combined

8

In [38]:
sal.head()

   OrderID ProductID  Qty  Amount Region Customer       City        Date
0     1001      P101    2   24000  south    Rahul  Bengaluru  2024-01-12
1     1002      P103    1    1500   west    Arjun     Mumbai  2024-01-13
2     1003      P102    3   45000  north   Shreya      Delhi  2024-01-14
3     1004      P104    1    1200   east    Meera    Kolkata  2024-01-15
4     1005      P105    1   55000  south    Anand    Chennai  2024-01-15

In [39]:
len(sal)

10

In [40]:
merge_inner=p.merge(sal,prod,on='ProductID',how='inner')

In [41]:
type(merge_inner)

pandas.core.frame.DataFrame

In [42]:
len(merge_inner)

10